require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/order_forms", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # OrderForm. As you add validations to OrderForm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # OrderFormsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      OrderForm.create! valid_attributes
      get order_forms_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      order_form = OrderForm.create! valid_attributes
      get order_form_url(order_form), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OrderForm" do
        expect {
          post order_forms_url,
               params: { order_form: valid_attributes }, headers: valid_headers, as: :json
        }.to change(OrderForm, :count).by(1)
      end

      it "renders a JSON response with the new order_form" do
        post order_forms_url,
             params: { order_form: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OrderForm" do
        expect {
          post order_forms_url,
               params: { order_form: invalid_attributes }, as: :json
        }.to change(OrderForm, :count).by(0)
      end

      it "renders a JSON response with errors for the new order_form" do
        post order_forms_url,
             params: { order_form: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested order_form" do
        order_form = OrderForm.create! valid_attributes
        patch order_form_url(order_form),
              params: { order_form: new_attributes }, headers: valid_headers, as: :json
        order_form.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the order_form" do
        order_form = OrderForm.create! valid_attributes
        patch order_form_url(order_form),
              params: { order_form: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the order_form" do
        order_form = OrderForm.create! valid_attributes
        patch order_form_url(order_form),
              params: { order_form: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested order_form" do
      order_form = OrderForm.create! valid_attributes
      expect {
        delete order_form_url(order_form), headers: valid_headers, as: :json
      }.to change(OrderForm, :count).by(-1)
    end
  end
end
